version: '3'

services:

  graphite:
    # https://github.com/graphite-project/docker-graphite-statsd
    # https://hub.docker.com/r/graphiteapp/graphite-statsd/
    # http://localhost:80
    image: graphiteapp/graphite-statsd:1.1.4-4
    container_name: graphite
    hostname: graphite
    volumes:
      - graphite-storage:/opt/graphite/storage
    ports:
      - 80:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126

  elasticsearch:
    # https://www.elastic.co/guide/en/elasticsearch/reference/6.4/docker.html
    # http://localhost:9200/
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  grafana:
    # http://docs.grafana.org/installation/docker/
    # http://localhost:3000
    image: grafana/grafana:5.3.1
    container_name: grafana
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_INSTALL_PLUGINS=jdbranham-diagram-panel
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - graphite
      - elasticsearch

  pygenerator:
    build: ./pygenerator
    container_name: pygenerator
    hostname: pygenerator
    depends_on:
      - graphite
      - elasticsearch
      - grafana

volumes:
  grafana-storage:
  elastic-storage:
  graphite-storage:
